export const CarsData = [
  {
    brand: "Toyota",
    modal: "Wigo",
    body_style: "Hatchback",
    variant: "TRD",
    price: 700000,
  },
  {
    brand: "Toyota",
    modal: "Wigo",
    body_style: "Hatchback",
    variant: "G",
    price: 658000,
  },
  {
    brand: "Toyota",
    modal: "Yaris",
    body_style: "Hatchback",
    variant: "S",
    price: 1114000,
  },
  {
    brand: "Toyota",
    modal: "Yaris",
    body_style: "Hatchback",
    variant: "E",
    price: 973000,
  },
  {
    brand: "Toyota",
    modal: "Vios",
    body_style: "Sedan",
    variant: "G",
    price: 970000,
  },
  {
    brand: "Toyota",
    modal: "Vios",
    body_style: "Sedan",
    variant: "XLE",
    price: 851000,
  },
  {
    brand: "Honda",
    modal: "Biro",
    body_style: "Hatchback",
    variant: "RS",
    price: 735000,
  },
  {
    brand: "Honda",
    modal: "Biro",
    body_style: "Hatchback",
    variant: "V",
    price: 661000,
  },
  {
    brand: "Honda",
    modal: "City",
    body_style: "Hatchback",
    variant: "RS",
    price: 1115000,
  },
  {
    brand: "Honda",
    modal: "City",
    body_style: "Sedan",
    variant: "V",
    price: 978000,
  },
  {
    brand: "Honda",
    modal: "Civic",
    body_style: "Sedan",
    variant: "RS",
    price: 1615000,
  },
  {
    brand: "Honda",
    modal: "Civic",
    body_style: "Sedan",
    variant: "E",
    price: 1188000,
  },
];
